<a href="https://colab.research.google.com/github/DikshyaL/DL-practical-lab/blob/main/COMP488P1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Assignment 1: Foundations & Tensor Operations**
* Name: Dikshya Lamichhane
* Course: COMP 488 - Neural Ntwork and Deep Learning
* Date: April 05, 2026
* Tools Used: NumPy, PyTorch
* Dataset: Synthetic data (generated using NumPy)

# Objectives
* Understand tensor operations using NumPy and PyTorch
* Perform reshaping and broadcasting operations
* Apply matrix multiplication and eigen value computation
* Compare manual computation using libraries
* Analyze numerical precision and probability concepts in ML

# Theoretical background

* **Scalers** :  Mathematics consists of manipulating numbers one at a time which are formally called as Scalers. We denote scalars by ordinary lower-cased letters (e.g. x,y, and z) and the space of all (continuous) real-valued scalars by R. Scalers are implemented as tensors that contian only one element. They are called 0th-order tensors.

* **Vectors** :
An array of numbers (scalers) arranged in order. Each no. is identified by an index. it is written in lower case bold such as **x**. They are called 1st-order tensors

* **Matrices** : 2D array of numbers. They are called 2nd-order tensors. WE denote matrices by bold capital letters (eg: **X**, **Y**, and **Z**) and represent them in code by tensors with two axes. If A has shape of height m and width n with real-
values then A ∈ R m*n

* **Tensors** : A tensor is an array of numbers arranged on a
regular grid with variable number of axes. Tensors give us a generic way of describing extensions to nth-order arrays.

* **Broadcasting** : Broadcasting allows operations between tensors of different shapes without explicit looping.

* **Matrix Multiplication**:
Fundamental operation in neural networks.We can think of the matrix–matrix multiplication AB as performing m matrix–vector products or m * n dot products and stitching the results together to form an n * m matrix.

* **Eigen vector** : An eigenvector of a square matrix A is a non-zero vector v such that multiplication by A only changesthe scale of v
Av=λv. The scalar λ is known as eigenvalue. If v is an eigenvector of A, so is any rescaled vector sv. Moreover sv still has the same eigen value.

* **Entropy**: Entropy measures uncertainty in a probability distribution:
H(p) = - Σ p(x) log p(x)

* **Normal Distribution**:
A common distribution in ML defined by mean and variance, often used in modeling data and initializing weights.


# Implementation
* Implemented tensor operations using NumPy and PyTorch
* Performed reshaping and broadcastinf operations
* Computed matrix multiplication and eigenvalues
* Compared manual and library-based computations
* Demosntrated floating point precision issues
* Implemented entropy and normal distribution examples

# Experiments
* Experiment 1: Tensor Operations

In [ ]:
# Tensor creation, reshaping, broadcasting

import numpy as np
import torch

# tensors using numpy and tensor

a_np = np.array([[1,2],[1,2]])
a_torch = torch.tensor([[3,4], [3,4]])

print("Numpy Tensor:\n", a_np)
print("Pytorch Tensor:\n", a_torch)

# reshaping the tensors

b_np = a_np.reshape(1,4)
b_torch = a_torch.reshape(1,4)

print("Reshaped Numpy Tensor(1,4):\n", b_np)
print("Reshaped Pytorch Tensor(1,4):\n", b_torch)

c_np = a_np.reshape(4,1)
c_torch = a_torch.reshape(4,1)

print("Reshaped Numpy Tensor(4,1):\n", c_np)
print("Reshaped Pytorch Tensor(4,1):\n", c_torch)


# boardcasting the tensors

vec_np = np.array([1, 2])
vec_torch = torch.tensor([1, 2])

print("Broadcasting with vector:")
d_np = a_np + vec_np
d_torch = a_torch + vec_torch

print("Broadcasted Numpy Tensor:\n", d_np)
print("Broadcasted Pytorch Tensor:\n", d_torch)


Numpy Tensor:
 [[1 2]
 [1 2]]
Pytorch Tensor:
 tensor([[3, 4],
        [3, 4]])
Reshaped Numpy Tensor(1,4):
 [[1 2 1 2]]
Reshaped Pytorch Tensor(1,4):
 tensor([[3, 4, 3, 4]])
Reshaped Numpy Tensor(4,1):
 [[1]
 [2]
 [1]
 [2]]
Reshaped Pytorch Tensor(4,1):
 tensor([[3],
        [4],
        [3],
        [4]])
Broadcasting with vector:
Broadcasted Numpy Tensor:
 [[2 4]
 [2 4]]
Broadcasted Pytorch Tensor:
 tensor([[4, 6],
        [4, 6]])


* Experiment 2: Matrix Multiplication

In [ ]:
# Matrix multiplication

import numpy as np
import torch

a_np = np.array([[1, 2], [3, 4]])
b_np = np.array([[5, 6], [7, 8]])

print("Numpy matrix multiplication:")
print(np.matmul(a_np, b_np))

c_torch = torch.tensor([[1, 2], [3, 4]])
d_torch = torch.tensor([[5, 6], [7, 8]])

print("Pytorch matrix multiplication:")
print(torch.matmul(c_torch, d_torch))



Numpy matrix multiplication:
[[19 22]
 [43 50]]
Pytorch matrix multiplication:
tensor([[19, 22],
        [43, 50]])



* Experiment 3: Eigenvalue computation

In [ ]:
# Eigenvalues

import numpy as np
import torch

a_np = np.array([[1, 2], [3, 4]])
a_torch = torch.tensor([[5, 6], [7, 8]])

eig_np = np.linalg.eig(a_np)
eig_torch = torch.linalg.eig(a_torch.float())

print("NumPy Eigenvalues:\n", eig_np)
print("PyTorch Eigenvalues:\n", eig_torch)

NumPy Eigenvalues:
 EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))
PyTorch Eigenvalues:
 torch.return_types.linalg_eig(
eigenvalues=tensor([-0.1521+0.j, 13.1521+0.j]),
eigenvectors=tensor([[-0.7587+0.j, -0.5928+0.j],
        [ 0.6515+0.j, -0.8054+0.j]]))



* Experiment 4: Manual vs library comparison along with probability and normal distribution

In [ ]:
# Manual vs library comparison (e.g., NumPy vs PyTorch)

import numpy as np
import torch

# Example 1: Mean
print("Example 1: Mean")
# Data
data = [1, 2, 3, 4, 5]

# Manual mean
manual_mean = sum(data) / len(data)

# NumPy
np_mean = np.mean(data)

# PyTorch
torch_mean = torch.mean(torch.tensor(data, dtype=torch.float32))

print("Manual Mean:", manual_mean)
print("NumPy Mean:", np_mean)
print("PyTorch Mean:", torch_mean)


# Example 2: Floating point Precision
print("Example 2: Floating point precision")
# Large + small number issue
a = 1e8
b = 1e-8

# NumPy
np_result = (a + b) - a

# PyTorch
torch_result = (torch.tensor(a) + torch.tensor(b)) - torch.tensor(a)

print("NumPy Result:", np_result)
print("PyTorch Result:", torch_result)


# Example 3: Probability distribution
print("Example 3: Probability distribution")
# Probability distribution (manual)
p = np.array([0.1, 0.2, 0.3, 0.4])

# Entropy (manual)
entropy_manual = -np.sum(p * np.log2(p))

# PyTorch entropy
p_torch = torch.tensor([0.1, 0.2, 0.3, 0.4])
entropy_torch = -torch.sum(p_torch * torch.log2(p_torch))

print("Manual Entropy:", entropy_manual)
print("PyTorch Entropy:", entropy_torch)


# Example 4: Normal distribution
print("Example 4: Normal distribution")

data_2 = np.random.normal(loc=0, scale=1, size=1000)

print("Mean:", np.mean(data_2))
print("Std Dev:", np.std(data_2))


Example 1: Mean
Manual Mean: 3.0
NumPy Mean: 3.0
PyTorch Mean: tensor(3.)
Example 2: Floating point precision
NumPy Result: 1.4901161193847656e-08
PyTorch Result: tensor(0.)
Example 3: Probability distribution
Manual Entropy: 1.8464393446710154
PyTorch Entropy: tensor(1.8464)
Example 4: Normal distribution
Mean: -0.03470471894970084
Std Dev: 0.9781115572758557


# Results:
The results show that NumPy and PyTorch produced consistent outputs for tensor creation, reshaping, broadcasting, and matrix multiplication.

Broadcasting worked correctly when operating on tensors of different shapes.

The matrix multiplication outputs matched across both libraries, confirming correct implementation.

The numerical precision experiment showed loss of small values when combined with large numbers, highlighting floating-point limitations.

Entropy values from manual and PyTorch computations were similar, and the normal distribution data had a mean close to 0 and standard deviation close to 1, as expected.


# Analysis and Discussion:
* Tensor Operations:
Tensors are the core data structure in ML models. Reshaping ensures compatibility between layers, while broadcasting simplifies operations like bias addition.

* Matrix Multiplication:
All neural networks rely on matrix multiplication for forward propagation.

* Numerical Precision:
Floating-point limitations can lead to instability, especially in deep learning. This is why normalization and stable computations are necessary.

* Probability Concepts:
Entropy quantifies uncertainty and is widely used in loss functions such as cross-entropy. Normal distribution is commonly assumed in ML models.

# Conclusion:

* Tensor operations, linear algebra, and probability form the core foundation of machine learning and deep learning systems
* Efficient tensor handling through reshaping and broadcasting enables scalable computation
* Matrix multiplication acts as the backbone of neural network operations
* Numerical precision plays a critical role in ensuring stable computations during model training
* Entropy and normal distribution are essential for modeling uncertainty and data behavior
* Understanding these concepts is crucial for building robust and efficient machine learning models